on:
  push:
     branches:
       - main

name: Deploy template app to shinyapps.io

jobs:
  deploy-shiny:
    name: Deploy to shinyapps.io
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install shiny
        run: |
          install.packages(c("shiny", "rsconnect"), type = "binary")
        shell: Rscript {0}
      - name: Push to shiny.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='lsinger-bio', token=${{secrets.SHINY_TOKEN}}, secret=${{secrets.SHINY_SECRET}})"
          Rscript -e "rsconnect::deployApp(appName = 'snashboard')" 
